services:
  app:
    image: ghcr.io/guenthereder/friedrich-salomon:latest
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - db-data:/app/data
      - uploads-data:/app/public/uploads
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 --label-enable
    restart: unless-stopped

volumes:
  db-data:
  uploads-data:
